"""add form templates

Revision ID: 8dcc6b1c7003
Revises: fe4373192423
Create Date: 2025-12-24 22:06:02.239350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dcc6b1c7003'
down_revision: Union[str, None] = 'fe4373192423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("field_type IN ('text','number','select','employee_reference','date')", name='ck_field_definitions_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_form_templates_name_version')
    )
    op.create_table('form_template_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_template_id', sa.UUID(), nullable=False),
    sa.Column('field_definition_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('override_label', sa.String(length=200), nullable=True),
    sa.Column('override_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_template_id', 'field_definition_id', name='uq_form_field_unique'),
    sa.UniqueConstraint('form_template_id', 'position', name='uq_form_field_position')
    )
    op.add_column('review_cycles', sa.Column('form_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'review_cycles', 'form_templates', ['form_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_cycles', type_='foreignkey')
    op.drop_column('review_cycles', 'form_template_id')
    op.drop_table('form_template_fields')
    op.drop_table('form_templates')
    op.drop_table('field_definitions')
    # ### end Alembic commands ###
