"""add review assignments

Revision ID: a2d9f41ab34d
Revises: 640f0107a9a2
Create Date: 2025-12-22 14:37:15.523105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d9f41ab34d'
down_revision: Union[str, None] = '640f0107a9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_employee_id', sa.UUID(), nullable=False),
    sa.Column('subject_employee_id', sa.UUID(), nullable=False),
    sa.Column('approver_employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_review_assignments_status'),
    sa.ForeignKeyConstraint(['approver_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'reviewer_employee_id', 'subject_employee_id', name='uq_assignment_cycle_reviewer_subject')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_assignments')
    # ### end Alembic commands ###
